Fix kolla/build.sh and kolla/deploy.sh
Kolla scripts require `docker` package instead of `docker-py`.
Otherwise, Ansible throws the following error:

* kolla/build.sh:

```
Traceback (most recent call last):
  File "/****/coriolis-docker/kolla/kolla/.venv/bin/kolla-build", line 10, in <module>
    sys.exit(main())
  File "/****/coriolis-docker/kolla/kolla/.venv/local/lib/python2.7/site-packages/kolla/cmd/build.py", line 30, in main
    statuses = build.run_build()
  File "/****/coriolis-docker/kolla/kolla/.venv/local/lib/python2.7/site-packages/kolla/image/build.py", line 1256, in run_build
    kolla = KollaWorker(conf)
  File "/****/coriolis-docker/kolla/kolla/.venv/local/lib/python2.7/site-packages/kolla/image/build.py", line 712, in __init__
    self.dc = docker.APIClient(version='auto', **docker_kwargs)
AttributeError: 'module' object has no attribute 'APIClient'
```

* kolla/deploy.sh:

```
Traceback (most recent call last):
  File "/tmp/ansible_5y5TfX/ansible_module_kolla_docker.py", line 906, in main
    dw = DockerWorker(module)
  File "/tmp/ansible_5y5TfX/ansible_module_kolla_docker.py", line 243, in __init__
    self.dc = get_docker_client()(**options)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 128, in __init__
    config_dict=self._general_configs, credstore_env=credstore_env,
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```