db migration: explicitly specify db engine and charset
Some of the db migration scripts specify the db engine (InnoDB) and
character set (utf-8).

When performing db sync as part of integration tests, the
migration scripts that do not specify the db engine/charset
fail, complaining about incompatible foreign keys:

    sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError)
    (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key
    constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
    [SQL:
    CREATE TABLE endpoint_region_mapping (
     id VARCHAR(36) NOT NULL,
     endpoint_id VARCHAR(36) NOT NULL,
     region_id VARCHAR(36) NOT NULL,
     created_at DATETIME,
     updated_at DATETIME,
     deleted_at DATETIME,
     deleted VARCHAR(36),
     PRIMARY KEY (id),
     FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
     FOREIGN KEY(region_id) REFERENCES region (id)
    )

For now, we'll just update those migration scripts to pass the db
engine and charset, which fixes the issue.

Note that we'll soon have to switch from sqlalchemy-migrate to
alembic.