Fix create_keystone_session method
When using the `v3token` plugin, the `user_domain_name` or
`user_domain_id` must not be set, otherwise the following error
is thrown when creating the Keystone v3 session:

```
Exception during message handling:
TypeError: __init__() got an unexpected keyword argument 'user_domain_name'
```

However, `user_domain_name` or `user_domain_id` are required
when using the other plugins (for example, the `v3password` plugin).